# Site settings

title: Direct speaking
author: 
  name: Na'eem Santiago
  email: naeem.santiago@rutgets.edu
description: Direct information about site building with Jekyll on Github pages

# Build settings

remote_theme: jekyll/minima
